CREATE TABLE `UserCredential` (
	`Uid` VARCHAR(45) NOT NULL,
    `Username` VARCHAR(45) NOT NULL,
    `Password` VARCHAR(45) NOT NULL,
    `UserType` VARCHAR(45) NOT NULL,
    PRIMARY KEY(`Uid`)
);

CREATE TABLE `Student` (
	`Sid` VARCHAR(45) NOT NULL,
    `FirstName` VARCHAR(45) NOT NULL,
    `LastName` VARCHAR(45) NOT NULL,
    PRIMARY KEY(`Sid`)
);

CREATE TABLE `Teacher` (
	`Tid` VARCHAR(45) NOT NULL,
    `FirstName` VARCHAR(45) NOT NULL,
    `LastName` VARCHAR(45) NOT NULL,
    PRIMARY KEY(`Tid`)
);

CREATE TABLE `Officer` (
	`Oid` VARCHAR(45) NOT NULL,
    `FirstName` VARCHAR(45) NOT NULL,
    `LastName` VARCHAR(45) NOT NULL,
    PRIMARY KEY(`Oid`)
);

ALTER TABLE Student
ADD FOREIGN KEY (`Sid`) REFERENCES UserCredential(`Uid`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE Teacher
ADD FOREIGN KEY (`Tid`) REFERENCES UserCredential(`Uid`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION;
    
ALTER TABLE Officer
ADD FOREIGN KEY (`Oid`) REFERENCES UserCredential(`Uid`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION;